version: '3.7'

services:
  mysql-db:
    build:
      context: .
      dockerfile: db.dockerfile
      no_cache: true
    container_name: mysql-db
    hostname: mysql-db
    restart: always
    networks:
    - backend
    volumes:
    - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  app:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    container_name: app
    restart: always
    networks:
      - frontend
      - backend
    depends_on:
    - mysql-db
    ports:
      - 5000:5000
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: "1234"
      MYSQL_DB: elmesary
      MYSQL_PORT: 3306
networks:
  frontend:
  backend:
    internal: true

volumes:
  db_data: